import { useEffect, useState } from 'react';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { IconCamera } from './Icons';

export default function QRScannerModal({ onClose }: { onClose: () => void }) {
  const [scanResult, setScanResult] = useState<string | null>(null);

  useEffect(() => {
    const scanner = new Html5QrcodeScanner(
      "reader",
      { fps: 10, qrbox: { width: 250, height: 250 } },
      /* verbose= */ false
    );

    scanner.render(
      (result) => {
        setScanResult(result);
        // Do not stop automatically so user can scan multiple if needed or see result
      },
      () => {
        // console.warn(error);
      }
    );

    return () => {
      scanner.clear().catch(err => console.error("Failed to clear scanner", err));
    };
  }, []);

  return (
    <div className="fixed inset-0 z-[60] bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="glass-panel w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh]">
        <div className="flex items-center justify-between p-4 border-b border-white/10">
          <h3 className="text-lg font-bold text-amber-400 flex items-center gap-2">
            <IconCamera className="w-5 h-5" /> Scan Receipt QR
          </h3>
          <button className="retro-btn" onClick={onClose}>Close</button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {!scanResult ? (
            <div id="reader" className="overflow-hidden rounded-xl border border-[#2c2c38]"></div>
          ) : (
            <div className="space-y-4">
              <div className="bg-green-500/10 border border-green-500/30 rounded-xl p-4">
                <p className="text-xs text-green-400 font-bold uppercase mb-2">Scan Successful</p>
                <div className="bg-[#0f0f18] p-3 rounded-lg text-sm text-gray-300 font-mono whitespace-pre-wrap break-all border border-[#2c2c38]">
                  {scanResult}
                </div>
              </div>
              <button className="print-btn w-full" onClick={() => setScanResult(null)}>
                Scan Another
              </button>
            </div>
          )}

          <div className="bg-[#1a1a28] p-4 rounded-xl">
            <p className="text-xs text-gray-500 leading-relaxed">
              <b>Tip:</b> Point your camera at any QR code generated by this app to see full bill details instantly.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
